default_language_version:
  python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml

-   repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
    -   id: isort

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
    - id: codespell

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.10
  hooks:
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]

- repo: https://github.com/collective/zpretty
  rev: 3.1.1
  hooks:
    - id: zpretty

