"""Change digram columns names and add compression

Revision ID: 26b8db5434ef
Revises: aad18e5848b0
Create Date: 2024-12-27 22:03:32.736845

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "26b8db5434ef"
down_revision = "aad18e5848b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("diagrams", "_code_version", new_column_name="code_version")
    op.alter_column("diagrams", "_code", new_column_name="code")
    op.alter_column("diagrams", "_code_is_valid", new_column_name="code_is_valid")
    op.alter_column("diagrams", "_image_version", new_column_name="image_version")
    op.alter_column("diagrams", "_image", new_column_name="image")

    op.execute("SET default_toast_compression=lz4")
    op.execute("ALTER TABLE diagrams ALTER COLUMN code SET COMPRESSION lz4")
    op.execute("ALTER TABLE diagrams ALTER COLUMN image SET COMPRESSION lz4")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("diagrams", "code_version", new_column_name="_code_version")
    op.alter_column("diagrams", "code", new_column_name="_code")
    op.alter_column("diagrams", "code_is_valid", new_column_name="_code_is_valid")
    op.alter_column("diagrams", "image_version", new_column_name="_image_version")
    op.alter_column("diagrams", "image", new_column_name="_image")
    # ### end Alembic commands ###
