"""

Revision ID: aad18e5848b0
Revises:
Create Date: 2024-12-23 08:10:20.311595

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "aad18e5848b0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("activated_at", sa.DateTime(), nullable=True),
        sa.Column("enabled", sa.Boolean(name="user_enabled_binary"), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "diagrams",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("_code_version", sa.BigInteger(), nullable=True),
        sa.Column("_code", sa.String(length=10240), nullable=True),
        sa.Column("_code_is_valid", sa.Boolean(), nullable=True),
        sa.Column("_image_version", sa.BigInteger(), nullable=True),
        sa.Column("_image", postgresql.BYTEA(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_diagrams_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diagrams")),
    )
    op.create_index(
        op.f("ix_diagrams_created_at"), "diagrams", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_diagrams_title"), "diagrams", ["title"], unique=False)
    op.create_index(
        op.f("ix_diagrams_updated_at"), "diagrams", ["updated_at"], unique=False
    )
    op.create_index(op.f("ix_diagrams_user_id"), "diagrams", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_diagrams_user_id"), table_name="diagrams")
    op.drop_index(op.f("ix_diagrams_updated_at"), table_name="diagrams")
    op.drop_index(op.f("ix_diagrams_title"), table_name="diagrams")
    op.drop_index(op.f("ix_diagrams_created_at"), table_name="diagrams")
    op.drop_table("diagrams")
    op.drop_table("users")
    # ### end Alembic commands ###
