"""remove _code_is_valid property from DB model

Revision ID: 5d3dee30022c
Revises: 76af1c6ef833
Create Date: 2025-02-21 18:37:59.655467

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5d3dee30022c"
down_revision = "76af1c6ef833"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("diagrams", "code_is_valid")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "diagrams",
        sa.Column("code_is_valid", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
